#!/usr/bin/env python3.6

def gather_info():
  height = float(input("What is your height ? (inches or meters)"))
  weight = float(input("What is your weight ? (pounds or kilograms)"))
  system = input("measurements in metric or imperial ?").lower().strip()
  return (height, weight, system)

def calculate_bmi(height, weight, system):
  if system == 'metric':
    bmi = (weight/(height**2))
  else:
    bmi = 703*(weight/(height**2))
  return bmi

while True:
  height,weight,system = gather_info()
  if system.startswith('i'):
    bmi = calculate_bmi(height, weight, system='imperial')
    print(f"bmi is {bmi}")
    break
  elif system.startswith('m'):
    bmi = calculate_bmi(height, weight, system='metric')
    print(f"bmi is {bmi}")
    break
  else:
    print("Error unknown measurement")

